version: '3.9'

services:

  frontend:
    build:
      context: frontend
      target: development
    ports:
      - "3000:3000"
    container_name: front
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: backend
      target: development
    container_name: back
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express
    ports: 
      - "3001:3001" 
  
  mongo:
    restart: always
    image: mongo:8.0
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    networks:
      - express-mongo
    ports:
      - "27017:27017"
  
  mongogui:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongogui
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongo 
    networks:
      - express-mongo

networks:
  react-express:
    driver: bridge
  express-mongo:
    driver: bridge 

volumes:
  mongo_data:
