version: '3.9'

services:

  db:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - banco_network
  
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - "80:80"
    networks:
      - banco_network
    depends_on:
      - db
  
  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver
    restart: always
    ports:
      - "8978:8978"
    networks:
      - banco_network
    depends_on:
      - db
    environment:
      - CB_SERVER_NAME=CloudBeaver Community
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace

volumes:
  postgres_data:
  cloudbeaver_data:

networks:
  banco_network:
    driver: bridge
